name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  security-events: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
              
    - name: Build with Gradle
      run: ./gradlew build
        
    - name: Archive Test Results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: build/reports/tests/test/
  
    - name: Download Test Results
      uses: actions/download-artifact@v2
      with:
        name: test-results
        path: test-results
    
    - name: Generate Javadoc
      run: ./gradlew javadoc

    - name: Archive Javadoc
      uses: actions/upload-artifact@v2
      with:
        name: javadoc
        path: build/docs/javadoc/  # Reemplaza con la ubicación real de tu Javadoc

    - name: Deploy to Javadoc Pages
      run: |
        mkdir -p gh-pages
        mv test-results gh-pages
        mv javadoc gh-pages
        cd gh-pages
        git init
        git config user.name "GitHub Actions"
        git config user.email "actions@users.noreply.github.com"
        git add .
        git commit -m "Deploy GitHub Pages"
        git push --force --quiet "https://${{ secrets.GITHUB_TOKEN }}"@github.com/juanmanuellosada/sportyfy-core.git javadoc-pages
